### ISSUE TITLE
netdev last_rx no longer working on newer kernel (like 4.13)

### ISSUE THREAD

**Issue by viisauksena** [freifunk-gluon/batman-adv-legacy#10]
got some errors when i recently try to build batman-adv for 
`linux-headers-4.13.0-kali1-amd64`

```
/home/k/wiki/freifunk/batman-adv-legacy/bridge_loop_avoidance.c:357:12: error: ‘struct net_device’ has no member named ‘last_rx’
  soft_iface->last_rx = jiffies;
            ^~



/home/k/wiki/freifunk/batman-adv-legacy/distributed-arp-table.c:861:23: error: ‘struct net_device’ has no member named ‘last_rx’
   bat_priv->soft_iface->last_rx = jiffies;
                       ^~


/home/k/wiki/freifunk/batman-adv-legacy/soft-interface.c:364:12: error: ‘struct net_device’ has no member named ‘last_rx’
  soft_iface->last_rx = jiffies;
            ^~
/home/k/wiki/freifunk/batman-adv-legacy/soft-interface.c: In function ‘batadv_softif_init_early’:
/home/k/wiki/freifunk/batman-adv-legacy/soft-interface.c:620:5: error: ‘struct net_device’ has no member named ‘destructor’; did you mean ‘priv_destructor’?
  dev->destructor = batadv_softif_free;
     ^~
```

the destructor thing was easyfixed - as suggested,
i commented out the `soft_iface->last_rx = jiffies;`  which is a dirty quickfix, while i couldnt find a replacement so far

here the git diff
```
cat gitdiff 
diff --git a/bridge_loop_avoidance.c b/bridge_loop_avoidance.c
index 492d006..3038e60 100644
--- a/bridge_loop_avoidance.c
+++ b/bridge_loop_avoidance.c
@@ -354,8 +354,7 @@ static void batadv_bla_send_claim(struct batadv_priv *bat_priv, uint8_t *mac,
 	batadv_inc_counter(bat_priv, BATADV_CNT_RX);
 	batadv_add_counter(bat_priv, BATADV_CNT_RX_BYTES,
 			   skb->len + ETH_HLEN);
-	soft_iface->last_rx = jiffies;
-
+/*	soft_iface->last_rx = jiffies;*/
 	netif_rx(skb);
 out:
 	if (primary_if)
diff --git a/distributed-arp-table.c b/distributed-arp-table.c
index 06345d4..b317726 100644
--- a/distributed-arp-table.c
+++ b/distributed-arp-table.c
@@ -858,7 +858,7 @@ bool batadv_dat_snoop_outgoing_arp_request(struct batadv_priv *bat_priv,
 						   bat_priv->soft_iface);
 		bat_priv->stats.rx_packets++;
 		bat_priv->stats.rx_bytes += skb->len + ETH_HLEN;
-		bat_priv->soft_iface->last_rx = jiffies;
+/*		bat_priv->soft_iface->last_rx = jiffies;*/
 
 		netif_rx(skb_new);
 		batadv_dbg(BATADV_DBG_DAT, bat_priv, "ARP request replied locally\n");
diff --git a/soft-interface.c b/soft-interface.c
index 3e3f81c..0394c81 100644
--- a/soft-interface.c
+++ b/soft-interface.c
@@ -361,7 +361,7 @@ void batadv_interface_rx(struct net_device *soft_iface,
 	batadv_add_counter(bat_priv, BATADV_CNT_RX_BYTES,
 			   skb->len + ETH_HLEN);
 
-	soft_iface->last_rx = jiffies;
+/*	soft_iface->last_rx = jiffies;*/
 
 	/* Let the bridge loop avoidance check the packet. If will
 	 * not handle it, we can safely push it up.
@@ -617,7 +617,7 @@ static void batadv_softif_init_early(struct net_device *dev)
 	ether_setup(dev);
 
 	dev->netdev_ops = &batadv_netdev_ops;
-	dev->destructor = batadv_softif_free;
+	dev->priv_destructor = batadv_softif_free;
 	dev->tx_queue_len = 0;
 
 	/* can't call min_mtu, because the needed variables
```

**Comment by viisauksena** [comment]
this may help https://patchwork.ozlabs.org/patch/716831/

> The network stack no longer uses the last_rx member of struct net_device
since the bonding driver switched to use its own private last_rx in
commit 9f242738376d ("bonding: use last_arp_rx in slave_last_rx()").

> However, some drivers still (ab)use the field for their own purposes and
some driver just update it without actually using it.

**Comment by NeoRaider** [comment]
I have backported the relevant patches. Note that this is not well-tested, but it compiles with both old and new kernels.
