### ISSUE TITLE
does not build with Kernel 5.4

### ISSUE THREAD

**Issue by cbricart** [freifunk-gluon/batman-adv-legacy#17]
while current HEAD builds fine up to Kernel 5.3.x it fails with Kernel 5.4 (which just went into Ubuntu 18.04 Bionic as their HWE-Kernel):

[make.log](https://github.com/freifunk-gluon/batman-adv-legacy/files/4958656/make.log)

```
..
CC [M]  /var/lib/dkms/batman-adv/2013.4.0/build/soft-interface.o
/var/lib/dkms/batman-adv/2013.4.0/build/soft-interface.c: In function ‘batadv_interface_rx’:
/var/lib/dkms/batman-adv/2013.4.0/build/soft-interface.c:319:2: error: implicit declaration of function ‘nf_reset’; did you mean ‘bio_reset’? [-Werror=implicit-function-declaration]
  nf_reset(skb);
  ^~~~~~~~
  bio_reset
```

**Comment by cbricart** [comment]
That one turned out to be an easy fix
